version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    resource_class: large
    steps:
      - checkout
      - run:
          name: Update packages
          command: apt-get update

      - restore_cache:
          key: v1-deps1-{{ checksum "opendrift_packages.yml" }}
      - run:
          name: Install requirements
          command: |
            if [ ! -e /opt/conda/envs/opendrift ]; then
              conda env create --file opendrift_packages.yml
              source activate opendrift_packages
            fi
      - save_cache:
          key: v1-deps1-{{ checksum "opendrift_packages.yml" }}
          paths:
            - "/opt/conda/envs"
      - run:
          name: Building opendrift-landmask-data
          command: source activate opendrift_packages && conda build opendrift-landmask-data

