{% set name = "roaring-landmask" %}
{% set version = "0.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/gauteh/roaring-landmask.git
  git_rev: "v{{ version }}"

build:
  number: 0
  script: "{{ PYTHON }} pip install ."
  noarch: python

requirements:
  build:
    - python >=3
    - maturin
  run:
    - python >=3

test:
  imports:
    - roaring_landmask

about:
  home: https://github.com/gauteh/roaring-landmask
  license: MIT
  summary: A fast and limited-memory structure with a landmask based on GSHHG for determing whether a point on Earth is on land or in the ocean

