{% set name = "opendrift-landmask-data" %}
{% set version = "0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/OpenDrift/opendrift-landmask-data.git
  git_rev: "v{{ version }}"

build:
  number: 1
  script: "{{ PYTHON }} setup.py build install"
  noarch: python

# XXX: relax libgdal and rasterio requirements once conda-forge / defaults channel consolidate better.
requirements:
  host:
    - python
    - setuptools
    - pytest
    - setuptools_scm
    - libgdal >=2.4
    - rasterio >=1.1
    - shapely
  run:
    - python
    - numpy
    - shapely
    - cartopy
    - libgdal >=2.4
    - rasterio >=1.1

test:
  imports:
    - opendrift_landmask_data

about:
  home: https://github.com/OpenDrift/opendrift-landmask-data
  license: GPLv2
  summary: Joined shapes of the GSHHS land data set for faster landmask shapes

