{% set name = "opendrift-landmask-data" %}
{% set version = "0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/OpenDrift/opendrift-landmask-data.git
  git_rev: "v{{ version }}"

build:
  number: 0
  script: "{{ PYTHON }} setup.py build install"
  noarch: python

requirements:
  build:
    - python >=3
    - setuptools
    - setuptools_scm
  run:
    - python >=3
    - numpy
    - shapely
    - affine

test:
  imports:
    - opendrift_landmask_data

about:
  home: https://github.com/OpenDrift/opendrift-landmask-data
  license: LGPLv3
  summary: Joined shapes of the GSHHS land data set for faster landmask shapes

