{% set name = "oil_library-opendrift" %}
{% set version = "1.1.1.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/OpenDrift/OilLibrary.git
  git_rev: 5862f10b1dfede8a52588f85e488e09ad0add3be

build:
  number: 1
  script: "{{ PYTHON }} setup.py install"
  noarch: python

requirements:
  build:
    - python >=3
    - numpy
    - scipy
    - setuptools
    - sqlalchemy
    - transaction
    - zope.sqlalchemy <1.2
    - awesome-slugify
    - unit_conversion
    - gitpython
  run:
    - python >=3
    - sqlalchemy
    - transaction
    - zope.sqlalchemy <1.2
    - awesome-slugify
    - unit_conversion

about:
  home: https://github.com/OpenDrift/OilLibrary
  license: Public Domain


