{% set name = "oil_library-opendrift" %}
{% set version = "2+noaa1.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/OpenDrift/OilLibrary.git
  git_rev: 2fce4ff019eaa8517a32795e9b815b59f54805a4

build:
  number: 0
  script: "{{ PYTHON }} setup.py install"
  noarch: python

requirements:
  build:
    - python >=3
    - numpy
    - scipy
    - setuptools
    - sqlalchemy
    - transaction
    - zope.sqlalchemy <1.2
    - awesome-slugify
    - unit_conversion
    - pytest
    - future
  run:
    - python >=3
    - numpy
    - scipy
    - sqlalchemy
    - transaction
    - zope.sqlalchemy <1.2
    - awesome-slugify
    - unit_conversion
    - future

test:
  imports:
    - oil_library

about:
  home: https://github.com/OpenDrift/OilLibrary
  license: Public Domain


