{% set name = "oil_library-opendrift" %}
{% set version = "4+noaa1.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/OpenDrift/OilLibrary.git
  git_rev: b57994c2101ea38063fa1765b2a9537abb756f2e

build:
  number: 0
  script: "{{ PYTHON }} setup.py install"
  noarch: python

requirements:
  build:
    - python >=3
    - numpy
    - scipy
    - setuptools
    - sqlalchemy>=1.3.7,<1.4
    - transaction
    - zope.sqlalchemy>=1.1
    - awesome-slugify>=1.6.5
    - unit_conversion
    - pytest
    - future
  run:
    - python >=3
    - numpy
    - scipy
    - sqlalchemy>=1.3.7,<1.4
    - transaction
    - zope.sqlalchemy>=1.1
    - awesome-slugify>=1.6.5
    - unit_conversion
    - future

test:
  imports:
    - oil_library

about:
  home: https://github.com/OpenDrift/OilLibrary
  license: Public Domain


