{% set name = "oil_library-opendrift" %}
{% set version = "1.1.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/OpenDrift/OilLibrary.git
  git_rev: e3274f15e36589d430c42c5c1421309e2b9e4b61

build:
  number: 1
  script: "{{ PYTHON }} setup.py install"
  noarch: python

requirements:
  build:
    - python >=3
    - numpy
    - scipy
    - setuptools
    - sqlalchemy
    - transaction
    - zope.sqlalchemy <1.2
    - awesome-slugify
    - unit_conversion
    - pytest
    - gitpython
  run:
    - numpy
    - python >=3
    - sqlalchemy
    - transaction
    - zope.sqlalchemy <1.2
    - awesome-slugify
    - unit_conversion
    - pytest

about:
  home: https://github.com/OpenDrift/OilLibrary
  license: Public Domain


