{% set name = "opendrift" %}
{% set version = "1.1.0rc2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/OpenDrift/opendrift.git
  git_rev: "v{{ version }}"

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python >=3
    - pip
    - setuptools
    - pytest
    - setuptools_scm
    - pytest
    - pytest-runner

  run:
    - python >=3
    - numpy
    - scipy
    - matplotlib
    - netCDF4
    - future
    - configobj
    - pillow
    - pyproj
    - cartopy
    - opendrift-landmask-data
    - oil_library-opendrift

about:
  home: https://github.com/OpenDrift/opendrift
  license: GPLv2
  summary: Open source framework for ocean trajectory modelling


