{% set name = "opendrift" %}
{% set version = "1.3.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/OpenDrift/opendrift.git
  git_rev: "v{{ version }}"

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  build:
    - python >=3
    - pip
    - setuptools
    - setuptools_scm

  run:
    - python >=3
    - numpy
    - scipy
    - matplotlib
    - netCDF4
    - configobj
    - pyproj
    - cartopy
    - nc-time-axis
    - opendrift-landmask-data>=0.6
    - oil_library-opendrift>=1.1.1.3
    - gdal>=3.1

about:
  home: https://github.com/OpenDrift/opendrift
  license: GPLv2
  summary: Open source framework for ocean trajectory modelling


