{% set name = "opendrift" %}
{% set version = "1.5.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/OpenDrift/opendrift.git
  git_rev: "v{{ version }}"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  build:
    - python>=3.7
    - pip
    - setuptools
    - setuptools_scm

  run:
    - python>=3.7
    - numpy
    - scipy
    - matplotlib
    - netCDF4
    - pyproj
    - cartopy
    - nc-time-axis
    - xarray
    - dask
    - xhistogram
    - opendrift-landmask-data>=0.7
    - oil_library-opendrift>=2+noaa1.1.3
    - gdal>=3.1
    - coloredlogs

about:
  home: https://github.com/OpenDrift/opendrift
  license: GPLv2
  summary: Open source framework for ocean trajectory modelling
