{% set name = "opendrift" %}
{% set version = "1.7.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/OpenDrift/opendrift.git
  git_rev: "v{{ version }}"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  build:
    - python>=3.7
    - pip
    - setuptools
    - setuptools_scm

  run:
    - python>=3.7
    - numpy
    - scipy>=1.6
    - matplotlib
    - netCDF4
    - pyproj
    - cartopy<0.20
    - nc-time-axis
    - geojson
    - xarray
    - dask
    - xhistogram
    - opendrift-landmask-data>=0.8
    - oil_library-opendrift>=4+noaa1.1.3
    - gdal>=3.1
    - coloredlogs
    - cfgrib
    - cmocean

test:
  imports:
    - opendrift_landmask_data
    - oil_library
    - opendrift

about:
  home: https://github.com/OpenDrift/opendrift
  license: GPLv2
  summary: Open source framework for ocean trajectory modelling
